name: EP
version: 1.0.0.0
author: "***REMOVED***"
maintainer: "***REMOVED***"
copyright: "2020 ***REMOVED***"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README.

dependencies:
  - base
  - clock
  - directory
  - either
  - formatting
  - process
  - random
  - split
  - text
  - config-ini
  - MonadRandom

library:
  source-dirs: src

executables:
  Task1:
    main: Task1.hs
    source-dirs: apps
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O3
      - -main-is Task1
    dependencies:
      - EP
      - config-ini
      - either
      - text
